export const SAREE_LIST_REQUEST =  'SAREE_LIST_REQUEST';
export const SAREE_LIST_SUCCESS =  'SAREE_LIST_SUCCESS';
export const SAREE_LIST_FAIL =  'SAREE_LIST_FAIL';

export const SAREE_DETAILS_REQUEST =  'SAREE_DETAILS_REQUEST';
export const SAREE_DETAILS_SUCCESS =  'SAREE_DETAILS_SUCCESS';
export const SAREE_DETAILS_FAIL =  'SAREE_DETAILS_FAIL';

export const SAREE_CREATE_REQUEST =  'SAREE_CREATE_REQUEST';
export const SAREE_CREATE_SUCCESS =  'SAREE_CREATE_SUCCESS';
export const SAREE_CREATE_FAIL =  'SAREE_CREATE_FAIL';
export const SAREE_CREATE_RESET =  'SAREE_CREATE_RESET';

export const SAREE_REVIEW_CREATE_REQUEST = 'SAREE_REVIEW_CREATE_REQUEST';
export const SAREE_REVIEW_CREATE_SUCCESS = 'SAREE_REVIEW_CREATE_SUCCESS';
export const SAREE_REVIEW_CREATE_FAIL = 'SAREE_REVIEW_CREATE_FAIL';
export const SAREE_REVIEW_CREATE_RESET = 'SAREE_REVIEW_CREATE_RESET';

export const SAREE_UPDATE_REQUEST =  'SAREE_UPDATE_REQUEST';
export const SAREE_UPDATE_SUCCESS =  'SAREE_UPDATE_SUCCESS';
export const SAREE_UPDATE_FAIL =  'SAREE_UPDATE_FAIL';
export const SAREE_UPDATE_RESET =  'SAREE_UPDATE_RESET';

export const SAREE_DELETE_REQUEST =  'SAREE_DELETE_REQUEST';
export const SAREE_DELETE_SUCCESS =  'SAREE_DELETE_SUCCESS';
export const SAREE_DELETE_FAIL =  'SAREE_DELETE_FAIL';
export const SAREE_DELETE_RESET =  'SAREE_DELETE_RESET';

export const SAREE_CATEGORY_LIST_REQUEST =  'SAREE_CATEGORY_LIST_REQUEST';
export const SAREE_CATEGORY_LIST_SUCCESS =  'SAREE_CATEGORY_LIST_SUCCESS';
export const SAREE_CATEGORY_LIST_FAIL =  'SAREE_CATEGORY_LIST_FAIL';
